config/routes.rb
Island::Application.routes.draw do
  resources :drag_and_drops

  resources :pages

  get "home/index"

  root :to => 'home#index'
  match '/0(.:format)' => 'pages#new'
  match '/:title' => 'pages#show'

end

app/models/drag_and_drop.rb
class DragAndDrop < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/drag_and_drops_controller.rb
class DragAndDropsController < ApplicationController
  # GET /drag_and_drops
  # GET /drag_and_drops.json
  def index
    @drag_and_drops = DragAndDrop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drag_and_drops }
    end
  end

  # GET /drag_and_drops/1
  # GET /drag_and_drops/1.json
  def show
    @drag_and_drop = DragAndDrop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @drag_and_drop }
    end
  end

  # GET /drag_and_drops/new
  # GET /drag_and_drops/new.json
  def new
    @drag_and_drop = DragAndDrop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @drag_and_drop }
    end
  end

  # GET /drag_and_drops/1/edit
  def edit
    @drag_and_drop = DragAndDrop.find(params[:id])
  end

  # POST /drag_and_drops
  # POST /drag_and_drops.json
  def create
    @drag_and_drop = DragAndDrop.new(params[:drag_and_drop])

    respond_to do |format|
      if @drag_and_drop.save
        format.html { redirect_to @drag_and_drop, notice: 'Drag and drop was successfully created.' }
        format.json { render json: @drag_and_drop, status: :created, location: @drag_and_drop }
      else
        format.html { render action: "new" }
        format.json { render json: @drag_and_drop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drag_and_drops/1
  # PUT /drag_and_drops/1.json
  def update
    @drag_and_drop = DragAndDrop.find(params[:id])

    respond_to do |format|
      if @drag_and_drop.update_attributes(params[:drag_and_drop])
        format.html { redirect_to @drag_and_drop, notice: 'Drag and drop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @drag_and_drop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drag_and_drops/1
  # DELETE /drag_and_drops/1.json
  def destroy
    @drag_and_drop = DragAndDrop.find(params[:id])
    @drag_and_drop.destroy

    respond_to do |format|
      format.html { redirect_to drag_and_drops_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = find_page_by_title(params[:title])

    unless @page
      new()
      return
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new
    @page.id = 0

    respond_to do |format|
      format.html { render action: "new" }  #new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    @page = Page.find(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create

	id = params[:page][:id]
	title = params[:page][:title]
	picture = params[:page][:picture]
	
	filename = picture.original_filename
	directory = 'public/uploads/users/' + title + '/'
	path = File.join(directory, filename)
	
	FileUtils.mkdir_p directory
	File.open(path, "wb") { |f| f.write(picture.read) }

	directory = '/' + directory
	
	@page = Page.create(:id=>id, :title=>title, :path=>path)
	
    respond_to do |format|
      if @page.save
        format.html { render action: "show" }
        format.json { render :json => @page.title }
      else
        format.html { render action: "show" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find(params[:id])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :no_content }
    end
  end
  
  # helper
  def find_page_by_title(title)
    for p in Page.all do
      if p.title == title
        return p
      end
    end
	return nil
  end

  def base_part_of(file_name)
    return File.basename(file_name, ".*")
  end
  
  def log(string)
    logger.info(string)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	def custom_assets(source, ext)
	  path = File.join(Rails.root, 'public', source) + ext
	  asset_id = File.exist?(path) ? File.mtime(path).to_i.to_s : ''
	  "#{source}?#{asset_id}"
	end
	
end

app/helpers/drag_and_drops_helper.rb
module DragAndDropsHelper
end

app/helpers/home_helper.rb
module HomeHelper

	def custom_assets(source, ext)
	  path = File.join(Rails.root, 'public', source) + ext
	  asset_id = File.exist?(path) ? File.mtime(path).to_i.to_s : ''
	  "#{source}?#{asset_id}"
	end
	
end

app/helpers/pages_helper.rb
module PagesHelper
  
end

app/views/drag_and_drops/_form.html.erb
<%= form_for(@drag_and_drop) do |f| %>
  <% if @drag_and_drop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@drag_and_drop.errors.count, "error") %> prohibited this drag_and_drop from being saved:</h2>

      <ul>
      <% @drag_and_drop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drag_and_drops/edit.html.erb
<h1>Editing drag_and_drop</h1>

<%= render 'form' %>

<%= link_to 'Show', @drag_and_drop %> |
<%= link_to 'Back', drag_and_drops_path %>

app/views/drag_and_drops/index.html.erb
<h1>Listing drag_and_drops</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @drag_and_drops.each do |drag_and_drop| %>
  <tr>
    <td><%= link_to 'Show', drag_and_drop %></td>
    <td><%= link_to 'Edit', edit_drag_and_drop_path(drag_and_drop) %></td>
    <td><%= link_to 'Destroy', drag_and_drop, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Drag and drop', new_drag_and_drop_path %>

app/views/drag_and_drops/new.html.erb
<h1>New drag_and_drop</h1>

<%= render 'form' %>

<%= link_to 'Back', drag_and_drops_path %>

app/views/drag_and_drops/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_drag_and_drop_path(@drag_and_drop) %> |
<%= link_to 'Back', drag_and_drops_path %>

app/views/home/index.html.erb
<%= javascript_include_tag :defaults %>

<%= sounds=[["sound1","a.mp3"], ["sound2", "b.mp3"]]%>

<%= toggle_sound "sound1" %>

<%= initialize_sounds(sounds, debug=true) %>
		
<script type="text/javascript">
	window.onload = function() { main(); };
	//window.onload = function() { Sound.test(); };
</script>

<canvas id="canvas" x="0" y="0" width="1530" height="718" />
<input id="myinput" type="file" class="droparea" name="thumbnail" data-canvas="true" />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Island</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Picture</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.picture %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>Upload an island</h1>
<%= form_for @page do |f| %>
<%=f.label :id %>
<%= label_tag("Title:") %>
  <%= f.text_field :title %>
  <p><%= label_tag("Picture:") %>
  <%= f.file_field :picture %></p>
  <p><%= f.submit %></p>
<% end %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

  <b>Picture:</b>
   
  <%= image_tag @page.path %>

<%= link_to 'Edit', edit_page_path(@page) %>
<%= link_to 'Back', pages_path %>